# Generated by Django 3.1.5 on 2021-03-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcs', '0001_initial'),
    ]
